### ISSUE TITLE
hub-tool logout produces scary error message when not logged in 

### ISSUE THREAD

**Issue by thaJeztah** [docker/hub-tool#154]
**Description**

When using `hub-tool logout`, an obscure error message is produced if I'm not currently logged in to Docker Hub

**Steps to reproduce the issue:**

```console
$ hub-tool login
Username: thajeztah
Password:
Login Succeeded

$ hub-tool logout
Logout Succeeded

$ hub-tool logout
Error: error erasing credentials - err: exit status 1, out: `error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.``
```

Note that the `docker` cli looks to have the same issue in similar conditions (also something we should fix), but provides slightly more details on what it's doing;

```console
$ docker logout
Removing login credentials for https://index.docker.io/v1/

$ docker logout
Removing login credentials for https://index.docker.io/v1/
WARNING: could not erase credentials:
https://index.docker.io/v1/: error erasing credentials - err: exit status 1, out: `error erasing credentials - err: exit status 1, out: `The specified item could not be found in the keychain.``
```

**Describe the results you received:**

A scary error message

**Describe the results you expected:**

Either;

1. the same message as when running a successful logout ("Logout Succeeded")
2. a message informing me that I was not logged in

Given that the end-result is the same for the user, I'm tempted to prefer `1.`, and consider `logout` to be idempotent

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker hub --version`:**

```
hub-tool --version
Docker Hub Tool v0.2.0, build 0edf43a
```

**Comment by moshebe** [comment]
I suggest this fix: #166 
I implemented @thaJeztah first suggestion using a little existence check when the erase fails.
Let me know what do you think 🙂
