### ISSUE TITLE
go install not working / metrics package not found

### ISSUE THREAD

**Issue by cmuench** [docker/hub-tool#163]
**Description**

I tried to install the tool with `go install github.com/docker/hub-tool`.
It's currently failing, because the package `github.com/docker/compose-cli/metrics` cannot be found.
I checked the metrics package. It seems that they reorganized the structure in the main branch.

**Steps to reproduce the issue:**
1. `go install github.com/docker/hub-tool`

**Describe the results you received:**

```
go/src/github.com/docker/hub-tool/internal/metrics/metrics.go:22:2: cannot find package "github.com/docker/compose-cli/metrics" in any of:
	/usr/lib/go/src/github.com/docker/compose-cli/metrics (from $GOROOT)
	/home/cmuench/go/src/github.com/docker/compose-cli/metrics (from $GOPATH)
```

**Describe the results you expected:**

Tool can be installed without an error.

**Output of `go version`:**
go version go1.15.7 linux/amd64

**Comment by ndeloof** [comment]
"metrics" package on compose-cli project has moved to https://github.com/docker/compose-cli/tree/main/cli/metrics
will move again, as we want this to be hosted by docker/cli

**Comment by rumpl** [comment]
@cmuench sorry about the hickup, can you try and run `GO111MODULE=on go get github.com/docker/hub-tool` and tell us if that works please?

**Comment by cmuench** [comment]
@rumpl That works. :+1:

**Comment by rumpl** [comment]
Great, we'll update the README, thanks!
