### ISSUE TITLE
repo rm command not working

### ISSUE THREAD

**Issue by zulhfreelancer** [docker/hub-tool#178]
**Description**

The `hub-tool repo rm my-username/my-repo` command is giving me `Error: Delete "https://hub.docker.com/v2/repositories/my-username/my-repo/": EOF` error.

When I tried with `hub-tool repo rm my-repo` (without my-username), I got `Error: operation not permitted` error.

**Steps to reproduce the issue:**
1. Run `hub-tool login`
2. Run `hub-tool repo rm USER/REPO`
3. Or run `hub-tool repo rm REPO`

**Describe the results you received:**

See above

**Describe the results you expected:**

The repo get deleted successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Always happen

**Output of `hub-tool --version`:**

```
Docker Hub Tool v0.4.1, build 5051946
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 75
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: G4YM:Y5PD:7E3Z:PJZS:URBX:MOMC:I7NO:5UUV:DLRK:7VKF:GQ7W:GHRL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Username: zulhfreelancer
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* OS: Mac OS 10.15.7
* Install method: direct download from [release page](https://github.com/docker/hub-tool/releases/tag/v0.4.1) and moved the binary to `/usr/local/bin`

**Comment by zulhfreelancer** [comment]
I also noticed that this `hub-tool repo rm` command doesn't have `--yes` or `--confirm` flag which will proceed without asking for user confirmation. Would be really nice if we can have this flag for automation purposes.

**Comment by silvin-lubecki** [comment]
Hello @zulhfreelancer , thank you for reporting this bug! 🤗 
I could reproduce it on my side. The bug has been introduced in the latest release `v0.4.1`, and the only change is the bump from golang 1.15 to golang 1.16. I downgraded to 1.15, and the bug disappeared. I need to investigate that.

**Comment by converge** [comment]
> I also noticed that this `hub-tool repo rm` command doesn't have `--yes` or `--confirm` flag which will proceed without asking for user confirmation. Would be really nice if we can have this flag for automation purposes.

The option `-f, --force` is available, ex:

```
hub-tool repo rm username/test -f
```
