### ISSUE TITLE
Error: username differs from your username, deletion aborted

### ISSUE THREAD

**Issue by zdhamasha** [docker/hub-tool#186]
hub-tool token rm $UUID

WARNING: This action is irreversible.
By confirming, you will permanently delete the access token.
Deleting a token will invalidate your credentials on all Docker clients currently authenticated with this token.

Please type your username "" to confirm deletion: developer
Error: "developer" differs from your username, deletion aborted

username is correct any idea ??

**Comment by converge** [comment]
Hi @zdhamasha , pls let me know if this fix works for you https://github.com/docker/hub-tool/pull/205
