### ISSUE TITLE
Release v0.4.4 download links are for v0.4.1

### ISSUE THREAD

**Issue by chjno** [docker/hub-tool#194]
**Description**

When I download hub-tool v0.4.4, the installed version I end up with is v0.4.1.
I attempted installing via hub-tool-darwin-amd64.tar.gz as well as by downloading the source code and compiling.

**Output of `hub-tool --version`:**

```
Docker Hub Tool v0.4.1, build 5051946
```

**Comment by mat007** [comment]
It works for me with the latest v0.4.4 on Windows and Mac Arm (sorry I don’t know where is my Mac Intel laptop 😬 but it shouldn’t be any different)

Are you sure you’re running the version you just downloaded?
If you have Docker Desktop installed, then you have a `hub-tool` in your path, so make sure to run `./hub-tool`.

**Comment by chjno** [comment]
Ah my bad, I didn't realize it was included with Docker Desktop! That was the issue, you can disregard :)
