### ISSUE TITLE
docker hub login fails

### ISSUE THREAD

**Issue by bounlu** [docker/hub-tool#195]
Typing the password correctly, login still fails:

```
hub-tool login xxxxxx

Password: 
Error: failed to authenticate: bad status code "400 Bad Request": malformed request: EOF
```

**Comment by ingshtrom** [comment]
Are you using a PAT (Personal Access Token) as the password? If you have two-factor authentication enabled, then you must use a PAT as the password, otherwise it will not work. 

Also, what version of `hub-tool` are you using?

Mine is:
```
🚀 hub-tool version
Version:    v0.4.4
Git commit: c9cb0ac822ad431a252d462d80ab0dcc21d49e6f

🚀 hub-tool login
Username: ahokanson
Password:
Login Succeeded
```

**Comment by bounlu** [comment]
2FA is not enabled on my account, so I am not using PAT as the password.

However, I found my version is a bit older, although I downloaded the latest release today:

```
$ hub-tool version
Version:    v0.4.1
Git commit: 505194662f8bb7e5b3cd500e3f98961097c4c3d7
```

Does it mean old version is packed in the latest release somehow?

**Comment by bounlu** [comment]
Ohh I see there is a conflict with the one that is installed via Docker Desktop.

Upgrading to the `v0.4.4` fixed the issue !
