### ISSUE TITLE
500 Internal Server Error on `hub-tool tag rm --force <tag name>`

### ISSUE THREAD

**Issue by scottmmjackson** [docker/hub-tool#196]
**Description**

`hub-tool tag rm --force` fails with `500 INTERNAL SERVER ERROR`

**Steps to reproduce the issue:**
1. `hub-tool login` with valid credentials
2. `hub-tool tag rm --force <tag to remove>`

**Describe the results you received:**

`500 INTERNAL SERVER ERROR`

**Describe the results you expected:**

`200 OK` and tags successfully removed

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens consistently. We have hub-tool running in CI and it has been occurring daily since yesterday.

**Output of `hub-tool --version`:** We're executing the following in CI:

```
  mkdir -p ~/bin
  curl -fsSL https://github.com/docker/hub-tool/releases/download/v0.4.4/hub-tool-linux-amd64.tar.gz \
    | tar -xz -O hub-tool/hub-tool \
    > ~/bin/hub-tool
  chmod +x ~/bin/hub-tool
  export PATH="${HOME}/bin:${PATH}"
```

**Output of `docker version`:**

None, this is on GHA `ubuntu-latest`

**Output of `docker info`:**

See above

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Github Actions `ubuntu-latest`

**Comment by silvin-lubecki** [comment]
Hello @scottmmjackson, I just tried to reproduce the bug but the deletion worked on my side. Could you retry 🙏

**Comment by scottmmjackson** [comment]
> Hello @scottmmjackson, I just tried to reproduce the bug but the deletion worked on my side. Could you retry 🙏 

Looks like it fixed itself. Thanks!
